language: python
python:
- "2.7"
services:
- mongodb
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source generationkwh ./setup.py test
after_success:
- coveralls

