language: python
python:
- "2.7"
- "3.4"
- "3.7"
services:
- mongodb
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install git+https://github.com/som-energia/plantmeter.git@master
script: coverage run --source generationkwh ./setup.py test
after_success:
- coveralls

