name: CI

on:
  push: # git push
  pull_request: # PR
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '2.7' # production
          - '3.8'
          - '3.9'
        mongodb-version:
          - 2
    name: Python ${{ matrix.python-version }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
      - name: Install dependencies
        run: |
          pip install https://files.pythonhosted.org/packages/3e/5c/2867e46f03d2fcc3d014a02eeb11ec55f3f8d9eddddcc5578ae8457f84f8/ERPpeek-1.7.1-py2.py3-none-any.whl
          pip install pytest-cov pytest
          ./setup.py develop
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls
            git+https://github.com/som-energia/plantmeter.git@master
      - name: Unit tests
        run: |
          pytest

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
