# This workflow will pass tests of module passed by input


name: Install Python 2.7.18 with pyenv
on: push


jobs:
  install_pyenv_python:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies for pyenv
      - name: Install Dependencies for pyenv
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            git \
            libssl-dev \
            zlib1g-dev

      # Step 3: Install pyenv
      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bashrc
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.bashrc
          echo 'eval "$(pyenv init --path)"' >> $HOME/.bashrc
          # Add to GitHub Actions environment variables
          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
          echo "PATH=$HOME/.pyenv/bin:$PATH" >> $GITHUB_ENV

      # Step 4: Install Python 2.7.18 with pyenv
      - name: Install Python 2.7.18
        env:
          PATH: ${{ env.PYENV_ROOT }}/bin:${{ env.PATH }}
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          export PYENV_ROOT="$HOME/.pyenv"
          eval "$(pyenv init --path)"
          pyenv install 2.7.18
          pyenv global 2.7.18

      # Step 5: Verify Python Installation
      - name: Verify Python Version
        env:
          PATH: ${{ env.PYENV_ROOT }}/shims:${{ env.PATH }}
        run: |
          export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"
          export PYENV_ROOT="$HOME/.pyenv"
          eval "$(pyenv init --path)"
          python --version

