# This workflow will pass tests of module passed by input

name: PROVA_WF
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pyenv
        run: |
          sudo apt-get update
          curl https://pyenv.run | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV


      - name: Create virtualenv
        env:
           PATH: ${{ env.PYENV_ROOT }}/bin:${{ env.PATH }}
        run: |
          echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
          eval "$(pyenv virtualenv-init -)"

          pyenv install 2.7.18
          pyenv global 2.7.18
          pyenv virtualenv 2.7.18 erp
          pyenv activate erp

          pip install --upgrade pip setuptools wheel

          pip install pudb

      - name: Activate virtualenv
        env:
           PATH: ${{ env.PYENV_ROOT }}/bin:${{ env.PATH }}
        run: |
          pyenv activate erp

      - name: Setup tmate session
        #if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
