# This workflow will pass tests of module passed by input


name: Install Python 2.7.18 with pyenv
on: push

env:
  PYENV_ROOT: /home/runner/.pyenv


jobs:
  install_pyenv_python:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies for pyenv
      - name: Install Dependencies for pyenv
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            git \
            libssl-dev \
            zlib1g-dev

      # Step 3: Install pyenv
      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          echo "$PYENV_ROOT/bin" >> $GITHUB_PATH
          echo "$PYENV_ROOT/shims" >> $GITHUB_PATH

      # Step 4: Install Python 2.7.18 with pyenv
      - name: Install Python 2.7.18
        run: |
          pyenv install 2.7.18
          pyenv global 2.7.18
          pip install --upgrade pip

      # Step 5: Verify Python Installation
      - name: Verify Python Version
        run: |
          python --version
          pip install pudb
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        if: ${{ failure() }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15

