# This workflow will pass tests of module passed by input

name: PROVA_WF
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev
          sudo ln -sf python2.7 /usr/bin/python
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
          python get-pip.py
          rm get-pip.py
          pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          pip install pudb
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
