# This workflow will pass tests of module passed by input

name: PROVA_WF
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v18  # https://github.com/marketplace/actions/pyenv-build
        with:
          default: "2.7"
          command: pip install -U pip  # upgrade pip after installing python
      - name: Install dependencies
        run: |
          pip install pudb
      - name: Setup tmate session
        #if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
